package com.yourname.smartpermissionanalyzer.domain.entities

data class AppEntity(
    val appName: String,
    val packageName: String,
    val appIconPath: String? = null,
    val permissions: List<String> = emptyList(),
    val detailedPermissions: List<String> = emptyList(),
    val riskLevel: RiskLevelEntity = RiskLevelEntity.UNKNOWN,
    val riskScore: Int = 0,
    val appCategory: AppCategoryEntity = AppCategoryEntity.UNKNOWN,
    val suspiciousPermissions: List<String> = emptyList(),
    val suspiciousPermissionCount: Int = 0,
    val criticalPermissionCount: Int = 0,
    val installTime: Long = 0L,
    val lastUpdateTime: Long = 0L,
    val lastUpdate: Long = 0L,
    val lastScannedTime: Long = 0L,
    val lastScan: Long = 0L,
    val isSystemApp: Boolean = false,
    val targetSdkVersion: Int = 0,
    val versionName: String = "Unknown",
    val versionCode: Int = 0,
    val minSdkVersion: Int = 0,
    val permissionDensity: Float = 0f,
    val riskFactors: List<String> = emptyList(),
    val permissionChanges: List<String> = emptyList(),
    val appSize: Long = 0L,
    val lastUsedTime: Long = 0L,
    val isEnabled: Boolean = true,
    val hasInternetAccess: Boolean = false,
    val signatureHash: String = "",
    val trustScore: Float = 0f
)
